### ISSUE TITLE
Update models

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ARCH2020_NLN_RE#1]
source: https://github.com/mforets/escritoire/tree/master/2020/Week22/ARCH_COMP_2020_NLN

**Comment by mforets** [comment]
- [x] coupled van der pol
- [x] Lotka volterra
- [x] production destruction
- [x] Laub loomis
- [x] quadrotor
- [x] spacecraft

only those models marked with cross are ready in this repo.
 
cc: @lbenet

**Comment by lbenet** [comment]
In #6 I've implemented the bechmark scripts of all models, except for the space rendezvous.

**Comment by lbenet** [comment]
The generation of the plots ~is still to be worked out~ is also addressed in #6.

EDIT: Update
